name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1

    - uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: '1.12.0.1479'
    - uses: actions/cache@v4.1.1
      with:
        path: ~/.m2
        key: default-build
    - run: clojure -X:dev:test
    - uses: codecov/codecov-action@v4.6.0
