name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: '1.11.1.1262'
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: default-build
    - run: clojure -T:build ci
    - uses: codecov/codecov-action@v3.1.1
